In [1]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine,text

In [2]:
database = 'DATA_SCIENCE'
servername = r'SerhanOztasAsus\SRNINTLSQLSERVER'
engine = create_engine(f"mssql+pyodbc://{servername}/{database}"
                       "?driver=ODBC+Driver+17+for+SQL+Server&trusted_connection=yes")
print(engine)

Engine(mssql+pyodbc://SerhanOztasAsus\SRNINTLSQLSERVER/DATA_SCIENCE?driver=ODBC+Driver+17+for+SQL+Server&trusted_connection=yes)

In [70]:
with engine.connect() as conn:
    df_messy_sales_orders = pd.read_sql(text('SELECT * FROM [DBO].[messy_sales_orders]'),conn)
    df_customer_reference = pd.read_sql(text('SELECT * FROM [dbo].[customer_reference]'),conn)
    df_product_reference  = pd.read_sql(text('SELECT * FROM [dbo].[product_reference]'),conn)
    df_region_targets     = pd.read_sql(text('SELECT * FROM [dbo].[region_targets]'),conn)



df_messy_sales_orders.reset_index()

,index,row_id,order_id,customer_id,customer_email,region,country,product_sku,product_name,sales_channel,...,discount_pct,tax_rate,shipping_cost,payment_method,coupon_code,fulfillment_status,notes,order_id_key,customer_id_key,product_sku_key
0,0,1,ORD-000001,CUST-00002,customer1@example.com,Europe,Germany,SKU-002,Bluetooth Speaker,Offline,...,0.01,0.060,5.74,CARD,,delivered,,ORD-000001,CUST-00002,SKU-002
1,1,2,ORD-000002,CUST-00003,customer2@example.com,Asia Pacific,Japan,SKU-003,Standing Desk,Online,...,0.02,0.070,6.49,PayPal,,delivered,,ORD-000002,CUST-00003,SKU-003
2,2,3,ORD-000003,CUST-00004,customer3@example.com,Latin America,Brazil,SKU-004,Coffee Grinder,Offline,...,0.03,0.080,7.24,wire,,delivered,,ORD-000003,CUST-00004,SKU-004
3,3,4,ORD-000004,CUST-00005,customer4@example.com,Middle East,UAE,SKU-005,Skin Care Kit,Online,...,0.04,0.090,7.99,Cash,,delivered,,ORD-000004,CUST-00005,SKU-005
4,4,5,ORD-000005,CUST-00006,customer5@example.com,Africa,South Africa,SKU-006,Yoga Mat,Offline,...,0.05,0.100,8.74,,NaN,delivered,,ORD-000005,CUST-00006,SKU-006
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11995,11995,11996,ORD-011996,CUST-00497,customer11996@example.com,Asia Pacific,Spain,SKU-005,Skin Care Kit,Online,...,0.26,0.130,24.49,Credit Card,,delivered,,ORD-011996,CUST-00497,SKU-005
11996,11996,11997,ORD-011997,CUST-00498,customer11997@example.com,latam,Kenya,SKU-006,Yoga Mat,Offline,...,0.27,0.050,25.24,Credit Card,,delivered,,ORD-011997,CUST-00498,SKU-006
11997,11997,11998,ORD-011998,CUST-00499,customer11998@example.com,Middle East,Australia,SKU-007,Camping Lamp,Online,...,0.28,0.060,25.99,Credit Card,N/A,delivered,,ORD-011998,CUST-00499,SKU-007
11998,11998,11999,ORD-011999,CUST-00500,customer11999@example.com,Africa,United States,SKU-008,SQL Handbook,Offline,...,0.29,0.070,26.74,credit card,BULK25,delivered,,ORD-011999,CUST-00500,SKU-008
11999,11999,12000,ORD-012000,CUST-00001,customer12000@example.com,North America,Germany,SKU-001,Notebook Pack,Online,...,0.00,0.080,27.49,CARD,NaN,delivered,,ORD-012000,CUST-00001,SKU-001

In [51]:
df_messy_sales_orders.loc[df_messy_sales_orders[df_messy_sales_orders.columns[2]].isnull()]

,row_id,order_id,customer_id,customer_email,region,country,product_sku,product_name,sales_channel,order_priority,...,discount_pct,tax_rate,shipping_cost,payment_method,coupon_code,fulfillment_status,notes,order_id_key,customer_id_key,product_sku_key
306,307,ORD-000307,NaN,customer307@example.com,Europe,Mexico,SKU-004,Coffee Grinder,Offline,C,...,0.07,0.060,25.24,Credit Card,,delivered,,ORD-000307,NaN,SKU-004
613,614,ORD-000614,NaN,customer614@example.com,Asia Pacific,Brazil,SKU-007,Camping Lamp,Online,L,...,0.14,0.070,19.24,wire,,delivered,,ORD-000614,NaN,SKU-007
920,921,ORD-000921,NaN,customer921@example.com,Latin America,Kenya,SKU-002,Bluetooth Speaker,Offline,M,...,0.21,0.080,13.24,Credit Card,,delivered,,ORD-000921,NaN,SKU-002
1227,1228,ORD-001228,NaN,customer1228@example.com,Middle East,France,SKU-005,Skin Care Kit,Online,H,...,0.28,0.090,7.24,Credit Card,,delivered,,ORD-001228,NaN,SKU-005
1534,1535,ORD-001535,NaN,customer1535@example.com,Africa,Germany,SKU-008,SQL Handbook,Offline,C,...,0.05,0.100,27.49,CARD,NaN,delivered,,ORD-001535,NaN,SKU-008
1841,1842,ORD-001842,NaN,customer1842@example.com,North America,India,SKU-003,Standing Desk,Online,L,...,0.12,0.110,21.49,Credit Card,,delivered,,ORD-001842,NaN,SKU-003
2148,2149,ORD-002149,NaN,customer2149@example.com,Europe,UAE,SKU-006,Yoga Mat,Offline,M,...,0.19,0.120,15.49,Cash,N/A,delivered,,ORD-002149,NaN,SKU-006
2455,2456,ORD-002456,NaN,customer2456@example.com,Asia Pacific,Australia,SKU-001,Notebook Pack,Online,H,...,0.26,0.130,9.49,Credit Card,,delivered,,ORD-002456,NaN,SKU-001
2762,2763,ORD-002763,NaN,customer2763@example.com,Latin America,Canada,SKU-004,Coffee Grinder,Offline,C,...,0.03,0.050,29.74,Credit Card,,delivered,,ORD-002763,NaN,SKU-004
3069,3070,ORD-003070,NaN,customer3070@example.com,Middle East,Japan,SKU-007,Camping Lamp,Online,L,...,0.10,0.060,23.74,PayPal,NaN,delivered,,ORD-003070,NaN,SKU-007
3376,3377,ORD-003377,NaN,customer3377@example.com,Africa,Spain,SKU-002,Bluetooth Speaker,Offline,urgent,...,0.17,0.070,17.74,Credit Card,welcome10,delivered,,ORD-003377,NaN,SKU-002
3683,3684,ORD-003684,NaN,customer3684@example.com,North America,South Africa,SKU-005,Skin Care Kit,Online,H,...,0.24,0.080,11.74,,,delivered,,ORD-003684,NaN,SKU-005
3990,3991,ORD-003991,NaN,customer3991@example.com,Europe,United States,SKU-008,SQL Handbook,Offline,C,...,0.01,0.090,5.74,credit card,BULK25,delivered,,ORD-003991,NaN,SKU-008
4297,4298,ORD-004298,NaN,customer4298@example.com,Asia Pacific,Mexico,SKU-003,Standing Desk,Online,L,...,0.08,0.100,25.99,Credit Card,N/A,delivered,,ORD-004298,NaN,SKU-003
4604,4605,ORD-004605,NaN,customer4605@example.com,Latin America,Brazil,SKU-006,Yoga Mat,Offline,M,...,0.15,0.110,19.99,wire,NaN,delivered,,ORD-004605,NaN,SKU-006
4911,4912,ORD-004912,NaN,customer4912@example.com,Middle East,Kenya,SKU-001,Notebook Pack,Online,H,...,0.22,0.120,13.99,Credit Card,,delivered,,ORD-004912,NaN,SKU-001
5218,5219,ORD-005219,NaN,customer5219@example.com,Africa,France,SKU-004,Coffee Grinder,online,C,...,0.29,0.130,7.99,Credit Card,FREESHIP,Delivered,,ORD-005219,NaN,SKU-004
5525,5526,ORD-005526,NaN,customer5526@example.com,North America,Germany,SKU-007,Camping Lamp,Online,L,...,0.06,0.050,28.24,CARD,,delivered,,ORD-005526,NaN,SKU-007
5832,5833,ORD-005833,NaN,CUSTOMER5833@Example.COM,north america,India,SKU-002,Bluetooth Speaker,WEB,M,...,0.13,0.060,22.24,Credit Card,,CANCELLED,,ORD-005833,NaN,SKU-002
6139,6140,ORD-006140,NaN,customer6140@example.com,Asia Pacific,UAE,SKU-005,Skin Care Kit,Online,H,...,0.20,0.070,16.24,Cash,NaN,delivered,,ORD-006140,NaN,SKU-005
6446,6447,ORD-006447,NaN,customer6447@example.com,Latin America,Australia,SKU-008,SQL Handbook,Offline,C,...,0.27,0.080,10.24,Credit Card,N/A,delivered,,ORD-006447,NaN,SKU-008
6753,6754,ORD-006754,NaN,customer6754@example.com,Middle East,Canada,SKU-003,Standing Desk,Online,urgent,...,0.04,0.090,30.49,Credit Card,welcome10,delivered,,ORD-006754,NaN,SKU-003
7060,7061,ORD-007061,NaN,customer7061@example.com,EUROPE,Japan,SKU-006,Yoga Mat,retail,M,...,0.11,0.100,24.49,PayPal,,returned,,ORD-007061,NaN,SKU-006
7367,7368,ORD-007368,NaN,customer7368@example.com,North America,Spain,SKU-001,Notebook Pack,Online,H,...,0.18,0.110,18.49,Credit Card,,delivered,,ORD-007368,NaN,SKU-001
7674,7675,ORD-007675,NaN,customer7675@example.com,Europe,South Africa,SKU-004,Coffee Grinder,Offline,C,...,0.25,0.120,12.49,,NaN,delivered,,ORD-007675,NaN,SKU-004
7981,7982,ORD-007982,NaN,customer7982@example.com,Asia Pacific,United States,SKU-007,Camping Lamp,Online,L,...,0.02,0.130,6.49,credit card,BULK25,delivered,,ORD-007982,NaN,SKU-007
8288,8289,ORD-008289,NaN,customer8289@example.com,Latin America,Mexico,SKU-002,Bluetooth Speaker,Offline,M,...,0.09,0.050,26.74,Credit Card,,delivered,,ORD-008289,NaN,SKU-002
8595,8596,ORD-008596,NaN,customer8596@example.com,Middle East,Brazil,SKU-005,Skin Care Kit,Online,H,...,0.16,0.060,20.74,wire,N/A,delivered,,ORD-008596,NaN,SKU-005
8902,8903,ORD-008903,NaN,customer8903@example.com,APAC,Kenya,SKU-008,SQL Handbook,Store,C,...,0.23,0.070,14.74,Credit Card,,pending,,ORD-008903,NaN,SKU-008
9209,9210,ORD-009210,NaN,customer9210@example.com,North America,France,SKU-003,Standing Desk,Online,L,...,0.00,0.080,8.74,Credit Card,NaN,delivered,,ORD-009210,NaN,SKU-003
9516,9517,ORD-009517,NaN,customer9517@example.com,latam,Germany,SKU-006,Yoga Mat,Offline,M,...,0.07,0.090,28.99,CARD,,delivered,,ORD-009517,NaN,SKU-006
9823,9824,ORD-009824,NaN,customer9824@example.com,Asia Pacific,India,SKU-001,Notebook Pack,Online,H,...,0.14,0.100,22.99,Credit Card,,delivered,,ORD-009824,NaN,SKU-001
10130,10131,ORD-010131,NaN,customer10131@example.com,Latin America,UAE,SKU-004,Coffee Grinder,Offline,urgent,...,0.21,0.110,16.99,Cash,welcome10,delivered,,ORD-010131,NaN,SKU-004
10437,10438,ORD-010438,NaN,customer10438@example.com,Middle East,Australia,SKU-007,Camping Lamp,online,L,...,0.28,0.120,10.99,Credit Card,FREESHIP,Delivered,,ORD-010438,NaN,SKU-007
10744,10745,ORD-010745,NaN,customer10745@example.com,Africa,Canada,SKU-002,Bluetooth Speaker,Offline,M,...,0.05,0.130,4.99,Credit Card,NaN,delivered,,ORD-010745,NaN,SKU-002
11051,11052,ORD-011052,NaN,customer11052@example.com,North America,Japan,SKU-005,Skin Care Kit,Online,H,...,0.12,0.050,25.24,PayPal,,delivered,,ORD-011052,NaN,SKU-005
11358,11359,ORD-011359,NaN,customer11359@example.com,Middle-East,Spain,SKU-008,SQL Handbook,Offline,C,...,0.19,0.060,19.24,Credit Card,,delivered,,ORD-011359,NaN,SKU-008
11665,11666,ORD-011666,NaN,CUSTOMER11666@Example.COM,north america,South Africa,SKU-003,Standing Desk,WEB,L,...,0.26,0.070,13.24,,,CANCELLED,,ORD-011666,NaN,SKU-003
11972,11973,ORD-011973,NaN,customer11973@example.com,Latin America,United States,SKU-006,Yoga Mat,Offline,M,...,0.03,0.080,7.24,credit card,BULK25,delivered,,ORD-011973,NaN,SKU-006

In [4]:
df_messy_sales_orders.columns

Index(['row_id', 'order_id', 'customer_id', 'customer_email', 'region',
       'country', 'product_sku', 'product_name', 'sales_channel',
       'order_priority', 'order_date', 'ship_date', 'units_sold', 'unit_price',
       'unit_cost', 'discount_pct', 'tax_rate', 'shipping_cost',
       'payment_method', 'coupon_code', 'fulfillment_status', 'notes',
       'order_id_key', 'customer_id_key', 'product_sku_key'],
      dtype='str')

In [5]:
# N/A, NA, null, None,"",""Lesson11-Refresh Connection.ipynb"

missing_words = ['', " ", "N/A", "NA", "null", "None", "n/a", "na", "Null", "NULL", "none", "NoneType", "not available"]

df_messy_sales_orders.columns

for column in df_messy_sales_orders.columns:
    #print(df_messy_sales_orders[column].dtype)
    df_messy_sales_orders[column] = df_messy_sales_orders[column].astype('string').str.strip()  # ltrim, rtrim and etc
    df_messy_sales_orders[column] = df_messy_sales_orders[column].replace(missing_words,pd.NA) 


#print(df_messy_sales_orders['coupon_code'] == ' welcome10 ')
df_messy_sales_orders['coupon_code'].str.contains('welcome10', case=False, na=False) 
# select distinct coupon_code,count(*) from messy_sales_orders where coupon_code like '%welcome10%' group by coupon_code

df_messy_sales_orders['coupon_code'].drop_duplicates() # 4 columns, 
df_messy_sales_orders['coupon_code'].unique()

# df_messy_sales_orders.loc[df_messy_sales_orders['coupon_code'].str.contains('welcome10', case=False, na=False), :].groupby('coupon_code').size().reset_index(name='count')
# select distinct coupon_code,count(*) from messy_sales_orders where coupon_code like '%welcome10%' group by coupon_code
df_messy_sales_orders.loc[df_messy_sales_orders['coupon_code'].isna() | df_messy_sales_orders['coupon_code']
                          .notnull() , :].groupby('coupon_code',dropna=False).size().reset_index(name='count')

# "" -> N/A

  coupon_code  count
0      BULK25    576
1    FREESHIP    406
2   welcome10    748
3        <NA>  10270

In [6]:


df_messy_sales_orders.groupby("coupon_code", dropna=False) \
    .size() \
    .fillna({"coupon_code": ""}).reset_index()

  coupon_code      0
0      BULK25    576
1    FREESHIP    406
2   welcome10    748
3        <NA>  10270

In [7]:
s = '  hello world    '
l = s.split(" ")
print(l)
print(s)
s = s.strip()
print(s)
l = s.split(" ")
print(l)

['', '', 'hello', 'world', '', '', '', '']
  hello world
hello world
['hello', 'world']

In [8]:
df_messy_sales_orders['discount_pct'] = df_messy_sales_orders['discount_pct']\
    .astype('str').replace('75%', '0.75')



# df_messy_sales_orders.loc[
#     df_messy_sales_orders["discount_pct"] == "75%",
#     "discount_pct"
# ] = "0.75"

df_messy_sales_orders.loc[
    df_messy_sales_orders["discount_pct"]== "0.75"]

,row_id,order_id,customer_id,customer_email,region,country,product_sku,product_name,sales_channel,order_priority,...,discount_pct,tax_rate,shipping_cost,payment_method,coupon_code,fulfillment_status,notes,order_id_key,customer_id_key,product_sku_key
108,109,ORD-000109,CUST-00110,customer109@example.com,Europe,South Africa,SKU-006,Yoga Mat,Offline,M,...,0.75,0.060,7.99,<NA>,<NA>,delivered,<NA>,ORD-000109,CUST-00110,SKU-006
217,218,ORD-000218,CUST-00219,customer218@example.com,Asia Pacific,Spain,SKU-003,Standing Desk,Online,L,...,0.75,0.070,10.99,Credit Card,<NA>,delivered,<NA>,ORD-000218,CUST-00219,SKU-003
326,327,ORD-000327,CUST-00328,customer327@example.com,Latin America,Japan,SKU-008,SQL Handbook,Offline,C,...,0.75,0.080,13.99,PayPal,<NA>,delivered,<NA>,ORD-000327,CUST-00328,SKU-008
435,436,ORD-000436,CUST-00437,customer436@example.com,Middle East,Canada,SKU-005,Skin Care Kit,Online,H,...,0.75,0.090,16.99,Credit Card,<NA>,delivered,<NA>,ORD-000436,CUST-00437,SKU-005
544,545,ORD-000545,CUST-00046,customer545@example.com,Africa,Australia,SKU-002,Bluetooth Speaker,Offline,M,...,0.75,0.100,19.99,Credit Card,<NA>,delivered,<NA>,ORD-000545,CUST-00046,SKU-002
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11444,11445,ORD-011445,CUST-00446,customer11445@example.com,Latin America,South Africa,SKU-006,Yoga Mat,Offline,M,...,0.75,0.110,4.99,<NA>,<NA>,delivered,<NA>,ORD-011445,CUST-00446,SKU-006
11553,11554,ORD-011554,CUST-00055,customer11554@example.com,Middle East,Spain,SKU-003,Standing Desk,Online,L,...,0.75,0.120,7.99,Credit Card,<NA>,delivered,<NA>,ORD-011554,CUST-00055,SKU-003
11771,11772,ORD-011772,CUST-00273,customer11772@example.com,North America,Canada,SKU-005,Skin Care Kit,Online,H,...,0.75,0.050,13.99,Credit Card,<NA>,delivered,<NA>,ORD-011772,CUST-00273,SKU-005
11880,11881,ORD-011881,CUST-00382,customer11881@example.com,Europe,Australia,SKU-002,Bluetooth Speaker,Offline,M,...,0.75,0.060,16.99,Credit Card,<NA>,delivered,<NA>,ORD-011881,CUST-00382,SKU-002
11989,11990,ORD-011990,CUST-00491,customer11990@example.com,Asia Pacific,UAE,SKU-007,Camping Lamp,Online,urgent,...,0.75,0.070,19.99,Cash,<NA>,delivered,<NA>,ORD-011990,CUST-00491,SKU-007

In [9]:
df_messy_sales_orders.loc[
    df_messy_sales_orders["discount_pct"]== '75%']

Empty DataFrame
Columns: [row_id, order_id, customer_id, customer_email, region, country, product_sku, product_name, sales_channel, order_priority, order_date, ship_date, units_sold, unit_price, unit_cost, discount_pct, tax_rate, shipping_cost, payment_method, coupon_code, fulfillment_status, notes, order_id_key, customer_id_key, product_sku_key]
Index: []

[0 rows x 25 columns]

In [10]:
df_messy_sales_orders.loc[3]

# .loc[conditions]
df_messy_sales_orders.loc[df_messy_sales_orders['row_id'].astype('int') < 3]

# select * from table where condition


df_messy_sales_orders.loc[df_messy_sales_orders['discount_pct'].astype('float')<0.01]

,row_id,order_id,customer_id,customer_email,region,country,product_sku,product_name,sales_channel,order_priority,...,discount_pct,tax_rate,shipping_cost,payment_method,coupon_code,fulfillment_status,notes,order_id_key,customer_id_key,product_sku_key
29,30,ORD-000030,CUST-00031,customer30@example.com,North America,UAE,SKU-007,Camping Lamp,Online,L,...,0.00,0.080,27.49,Cash,<NA>,delivered,<NA>,ORD-000030,CUST-00031,SKU-007
59,60,ORD-000060,CUST-00061,customer60@example.com,North America,Mexico,SKU-005,Skin Care Kit,Online,H,...,0.00,0.110,23.74,Credit Card,<NA>,delivered,<NA>,ORD-000060,CUST-00061,SKU-005
89,90,ORD-000090,CUST-00091,customer90@example.com,North America,Australia,SKU-003,Standing Desk,Online,L,...,0.00,0.050,19.99,Credit Card,<NA>,delivered,<NA>,ORD-000090,CUST-00091,SKU-003
102,103,ORD-000103,CUST-00104,customer103@example.com,Europe,Australia,SKU-008,SQL Handbook,Offline,C,...,-0.05,0.090,29.74,Credit Card,<NA>,delivered,<NA>,ORD-000103,CUST-00104,SKU-008
119,120,ORD-000120,CUST-00121,customer120@example.com,North America,Brazil,SKU-001,Notebook Pack,Online,H,...,0.00,0.080,16.24,wire,<NA>,delivered,<NA>,ORD-000120,CUST-00121,SKU-001
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11909,11910,ORD-011910,CUST-00411,customer11910@example.com,North America,Japan,SKU-007,Camping Lamp,Online,L,...,0.00,0.080,12.49,PayPal,<NA>,delivered,<NA>,ORD-011910,CUST-00411,SKU-007
11939,11940,ORD-011940,CUST-00441,customer11940@example.com,North America,France,SKU-005,Skin Care Kit,Online,<NA>,...,0.00,0.110,FREE,Credit Card,<NA>,delivered,<NA>,ORD-011940,CUST-00441,SKU-005
11947,11948,ORD-011948,CUST-00449,customer11948@example.com,APAC,Germany,SKU-005,Skin Care Kit,Store,H,...,-0.05,0.100,14.74,CARD,<NA>,pending,<NA>,ORD-011948,CUST-00449,SKU-005
11969,11970,ORD-011970,CUST-00471,CUSTOMER11970@Example.COM,north america,Spain,SKU-003,Standing Desk,WEB,L,...,0.00,0.050,4.99,Credit Card,<NA>,CANCELLED,<NA>,ORD-011970,CUST-00471,SKU-003
11999,12000,ORD-012000,CUST-00001,customer12000@example.com,North America,Germany,SKU-001,Notebook Pack,Online,H,...,0.00,0.080,27.49,CARD,<NA>,delivered,<NA>,ORD-012000,CUST-00001,SKU-001

APAC = Asia Pasific

In [11]:
df_messy_sales_orders_distinct_region = df_messy_sales_orders['region'].drop_duplicates()
df_messy_sales_orders_distinct_region

0             Europe
1       Asia Pacific
2      Latin America
3        Middle East
4             Africa
5      North America
18     north america
22            EUROPE
28              APAC
30             latam
36       Middle-East
40            AFRICA
210             <NA>
Name: region, dtype: string

In [12]:
# df_messy_sales_orders['region'] = df_messy_sales_orders["region"].replace({
#         'APAC': 'Asia Pacific',
#         'latam': 'Latin America',
#         'AFRICA': 'Africa',
#         'Middle-East': 'Middle East',
#         'north america': 'North America',
#         'EUROPE': 'Europe'
#     })
# df_messy_sales_orders_distinct_region=df_messy_sales_orders['region'].drop_duplicates()
# df_messy_sales_orders_distinct_region

# df_messy_sales_orders.loc[df_messy_sales_orders['region'].astype('str')=='APAC']

In [13]:
df_messy_sales_orders.head()

,row_id,order_id,customer_id,customer_email,region,country,product_sku,product_name,sales_channel,order_priority,...,discount_pct,tax_rate,shipping_cost,payment_method,coupon_code,fulfillment_status,notes,order_id_key,customer_id_key,product_sku_key
0,1,ORD-000001,CUST-00002,customer1@example.com,Europe,Germany,SKU-002,Bluetooth Speaker,Offline,M,...,0.01,0.060,5.74,CARD,<NA>,delivered,<NA>,ORD-000001,CUST-00002,SKU-002
1,2,ORD-000002,CUST-00003,customer2@example.com,Asia Pacific,Japan,SKU-003,Standing Desk,Online,L,...,0.02,0.070,6.49,PayPal,<NA>,delivered,<NA>,ORD-000002,CUST-00003,SKU-003
2,3,ORD-000003,CUST-00004,customer3@example.com,Latin America,Brazil,SKU-004,Coffee Grinder,Offline,C,...,0.03,0.080,7.24,wire,<NA>,delivered,<NA>,ORD-000003,CUST-00004,SKU-004
3,4,ORD-000004,CUST-00005,customer4@example.com,Middle East,UAE,SKU-005,Skin Care Kit,Online,H,...,0.04,0.090,7.99,Cash,<NA>,delivered,<NA>,ORD-000004,CUST-00005,SKU-005
4,5,ORD-000005,CUST-00006,customer5@example.com,Africa,South Africa,SKU-006,Yoga Mat,Offline,M,...,0.05,0.100,8.74,<NA>,<NA>,delivered,<NA>,ORD-000005,CUST-00006,SKU-006

In [14]:
region_values = {
        'APAC': 'Asia Pacific',
        'latam': 'Latin America',
        'AFRICA': 'Africa',
        'Middle-East': 'Middle East',
        'north america': 'North America',
        'EUROPE': 'Europe'
    }

# row_id, order_id, and 23 columns.
# 
for value in region_values:
    print(value)
    print(region_values[value])
    print('-'*5)
    df_messy_sales_orders['region'] = df_messy_sales_orders['region'].replace(value, region_values[value])

df_messy_sales_orders_distinct_region = df_messy_sales_orders['region'].drop_duplicates()
df_messy_sales_orders_distinct_region

APAC
Asia Pacific
-----
latam
Latin America
-----
AFRICA
Africa
-----
Middle-East
Middle East
-----
north america
North America
-----
EUROPE
Europe
-----

0             Europe
1       Asia Pacific
2      Latin America
3        Middle East
4             Africa
5      North America
210             <NA>
Name: region, dtype: string

In [15]:
df_messy_sales_orders['region'] = df_messy_sales_orders["region"].replace({
        'APAC': 'Asia Pacific',
        'latam': 'Latin America',
        'AFRICA': 'Africa',
        'Middle-East': 'Middle East',
        'north america': 'North America',
        'EUROPE': 'Europe'
    })

df_messy_sales_orders['region'] = df_messy_sales_orders['region'].fillna('Unknown')
df_messy_sales_orders['region'].drop_duplicates()

0             Europe
1       Asia Pacific
2      Latin America
3        Middle East
4             Africa
5      North America
210          Unknown
Name: region, dtype: string

In [16]:
df_messy_sales_orders['sales_channel'].drop_duplicates()


sales_channel_values = {
    'online': 'Online',
    'retail': 'Retail',
    'WEB': 'Web'
}

df_messy_sales_orders['sales_channel'] = df_messy_sales_orders['sales_channel'].replace(
    {
    'online': 'Online',
    'retail': 'Retail',
    'WEB': 'Web'
    }
)

df_messy_sales_orders['sales_channel'] = df_messy_sales_orders['sales_channel'].fillna('Unknown')
df_messy_sales_orders['sales_channel'].drop_duplicates()

0      Offline
1       Online
18         Web
22      Retail
28       Store
166    Unknown
Name: sales_channel, dtype: string

In [ ]:
columns = df_messy_sales_orders.columns
df_column_values = []
for column in columns:
    if column not in ('row_id', 'order_id', 'customer_id','order_id_key', 'customer_id_key', 'product_sku_key','customer_email','notes'):
        df_column_values.append(df_messy_sales_orders[column].drop_duplicates())
# for column in df_messy_sales_orders.columns:
#     for values in column:  
#         print(column)
#         print(values)
print(df_column_values[3])
# for val in df_column_values:
#     print(val[0])

0      SKU-002
1      SKU-003
2      SKU-004
3      SKU-005
4      SKU-006
5      SKU-007
6      SKU-008
7      SKU-001
112       <NA>
138    sku-001
148    SKU-404
Name: product_sku, dtype: string

In [30]:
df_messy_sales_orders['product_sku'] = df_messy_sales_orders['product_sku'].fillna('Unknown')

df_messy_sales_orders['product_sku'].drop_duplicates()

df_messy_sales_orders['product_sku'] = df_messy_sales_orders['product_sku'].replace('Unknow','Unknown')
df_messy_sales_orders['product_sku'].drop_duplicates()

0      SKU-002
1      SKU-003
2      SKU-004
3      SKU-005
4      SKU-006
5      SKU-007
6      SKU-008
7      SKU-001
112    Unknown
138    sku-001
148    SKU-404
Name: product_sku, dtype: string

In [53]:
df_messy_sales_orders.columns[1]

'order_id'

In [71]:
df_messy_sales_orders.columns

df_messy_sales_orders = df_messy_sales_orders.fillna('Unknown')
# select row_id, order_id from sales where proprodduucct_sku = 'unknown'
df_messy_sales_orders.loc[df_messy_sales_orders[df_messy_sales_orders.columns[2]].isnull()]

Empty DataFrame
Columns: [row_id, order_id, customer_id, customer_email, region, country, product_sku, product_name, sales_channel, order_priority, order_date, ship_date, units_sold, unit_price, unit_cost, discount_pct, tax_rate, shipping_cost, payment_method, coupon_code, fulfillment_status, notes, order_id_key, customer_id_key, product_sku_key]
Index: []

[0 rows x 25 columns]

In [72]:
df_messy_sales_orders['unit_price'].drop_duplicates()

0         214.91
1         347.57
2          28.82
3          16.38
4          80.10
5         118.29
6          20.70
7          13.94
8         234.91
9         379.53
10         31.44
11         17.85
12         87.22
13        128.69
14         22.50
15         15.14
16        254.90
17        411.49
18         34.06
19         19.32
20         94.34
21        139.09
22         24.30
23         16.34
24        274.89
25        443.45
26         36.68
27         20.79
28        101.46
29        149.49
30         26.10
31         17.54
32        294.88
33        475.41
34         39.30
35         22.26
36        108.58
37        159.89
38         27.90
39         12.74
166      Unknown
172          N/A
178    $1,299.99
190          -45
196            0
Name: unit_price, dtype: str

In [81]:
df_messy_sales_orders['unit_price']=df_messy_sales_orders['unit_price'].replace('Unknown', pd.NA)
# $1,299.99, 1234.333
df_messy_sales_orders['unit_price'] = pd.to_numeric(
    df_messy_sales_orders['unit_price'].astype('string').str.replace("$", "").str.replace(',', ''),
    errors='coerce'
)
df_messy_sales_orders['unit_price'].drop_duplicates()

0       214.91
1       347.57
2        28.82
3        16.38
4         80.1
5       118.29
6         20.7
7        13.94
8       234.91
9       379.53
10       31.44
11       17.85
12       87.22
13      128.69
14        22.5
15       15.14
16       254.9
17      411.49
18       34.06
19       19.32
20       94.34
21      139.09
22        24.3
23       16.34
24      274.89
25      443.45
26       36.68
27       20.79
28      101.46
29      149.49
30        26.1
31       17.54
32      294.88
33      475.41
34        39.3
35       22.26
36      108.58
37      159.89
38        27.9
39       12.74
166       <NA>
178    1299.99
190      -45.0
196        0.0
Name: unit_price, dtype: Float64